# 파일 위치: src/main/resources/application.yml
spring:
  # 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/syncband
    username: postgres
    password: gg940701
    driver-class-name: org.postgresql.Driver
  
  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # 개발 환경에서는 update, 운영 환경에서는 validate로 변경
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  
  # Flyway 마이그레이션 설정
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    
  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# 서버 포트 설정
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

# JWT 토큰 설정
jwt:
  secret: syncband_secure_key_for_jwt_token_please_change_in_production
  expiration: 86400000 # 24시간 (밀리초)

# 파일 업로드 경로 설정
file:
  upload-dir: uploads

# 로깅 설정
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    com.syncband: DEBUG

# WebSocket 설정
websocket:
  allowed-origins: "*"
  endpoint: "/ws"
  application-destination-prefixes: "/app"
  simple-broker: "/topic, /queue"